#!/usr/bin/env bash
# Regenerate INDEX.md — a discoverability manifest for external readers (e.g., Claude Chat)
# that cannot crawl GitHub's directory tree URLs due to robots.txt.
#
# Run from anywhere; the script resolves the repo root via git.
# Usage: ./scripts/regen-index.sh
#
# Pre-commit hook integration (optional):
#   ln -s ../../scripts/regen-index.sh .git/hooks/pre-commit
# then INDEX.md regenerates on every commit and stages itself.

set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"
cd "$REPO_ROOT"

# Resolve owner/repo and default branch from origin URL
ORIGIN_URL="$(git config --get remote.origin.url)"
case "$ORIGIN_URL" in
    git@github.com:*)
        SLUG="${ORIGIN_URL#git@github.com:}"
        ;;
    https://github.com/*)
        SLUG="${ORIGIN_URL#https://github.com/}"
        ;;
    *)
        echo "regen-index: unrecognized origin URL: $ORIGIN_URL" >&2
        exit 1
        ;;
esac
SLUG="${SLUG%.git}"

BRANCH="$(git symbolic-ref --short HEAD 2>/dev/null || echo main)"
API_URL="https://api.github.com/repos/${SLUG}/git/trees/${BRANCH}?recursive=1"
RAW_BASE="https://raw.githubusercontent.com/${SLUG}/${BRANCH}"
WEB_BASE="https://github.com/${SLUG}/blob/${BRANCH}"

OUT="$REPO_ROOT/INDEX.md"

{
    echo "# Repository Index"
    echo
    echo "*Generated by \`scripts/regen-index.sh\`; do not edit by hand.*"
    echo "*Last regenerated: $(date -u '+%Y-%m-%d %H:%M UTC')*"
    echo
    echo "This file exists so external readers (e.g., Claude Chat) can discover the repo's contents without crawling GitHub's directory tree URLs, which are disallowed by \`robots.txt\`."
    echo
    echo "## Discovery routes"
    echo
    echo "**1. GitHub API (programmatic, always current):**"
    echo
    echo "\`\`\`"
    echo "$API_URL"
    echo "\`\`\`"
    echo
    echo "Returns the full file tree as JSON in a single call. Each entry's \`path\` field can be appended to the raw base below to fetch the file."
    echo
    echo "**2. Raw content base (per-file fetch):**"
    echo
    echo "\`\`\`"
    echo "$RAW_BASE/{path}"
    echo "\`\`\`"
    echo
    echo "**3. This manifest (human-readable, committed fallback):**"
    echo
    echo "Each path below is linked to its raw URL. Grouped by top-level directory."
    echo
    echo "---"
    echo

    # Group tracked files by top-level path (dir or root file)
    PREV_GROUP=""
    git ls-files | sort | while IFS= read -r path; do
        # Determine group: top-level directory, or "(root)" for root files
        if [[ "$path" == */* ]]; then
            GROUP="${path%%/*}/"
        else
            GROUP="(root)"
        fi

        if [[ "$GROUP" != "$PREV_GROUP" ]]; then
            if [[ -n "$PREV_GROUP" ]]; then
                echo
            fi
            echo "## \`$GROUP\`"
            echo
            PREV_GROUP="$GROUP"
        fi

        # URL-encode spaces in path (rare in this repo; safe regardless)
        ENCODED="${path// /%20}"
        echo "- [\`$path\`]($RAW_BASE/$ENCODED) | [view on GitHub]($WEB_BASE/$ENCODED)"
    done

    echo
    echo "---"
    echo
    echo "*Total tracked files: $(git ls-files | wc -l | tr -d ' ')*"
    echo "*Branch: \`$BRANCH\`*"
} > "$OUT"

echo "regen-index: wrote $OUT ($(wc -l < "$OUT") lines, $(git ls-files | wc -l | tr -d ' ') file entries)"

# If invoked as a pre-commit hook, stage the regenerated index
if [[ "${1:-}" == "--stage" ]] || [[ "$(basename "${0:-}")" == "pre-commit" ]]; then
    git add "$OUT"
fi
